export const weather = {
  REQUESTED_CITY_ON_TOP: "REQUESTED_CITY_ON_TOP",
  REQUEST_CITY_WEATHER: "REQUEST_CITY_WEATHER",
  REQUEST_CITY_WEATHER_PENDING: "REQUEST_CITY_WEATHER_PENDING",
  REQUEST_CITY_WEATHER_FULFILLED: "REQUEST_CITY_WEATHER_FULFILLED",
  REQUEST_CITY_WEATHER_REJECTED: "REQUEST_CITY_WEATHER_REJECTED",

  REQUEST_DETAILED_WEATHER: "REQUEST_DETAILED_WEATHER",
  REQUEST_DETAILED_WEATHER_PENDING: "REQUEST_DETAILED_WEATHER_PENDING",
  REQUEST_DETAILED_WEATHER_FULFILLED: "REQUEST_DETAILED_WEATHER_FULFILLED",
  REQUEST_DETAILED_WEATHER_REJECTED: "REQUEST_DETAILED_WEATHER_REJECTED",
};
